### ISSUE TITLE
Docs show data instead of newtype

### ISSUE THREAD

**Issue by andrewthad** [spl/dlist#24]
For some reason, the [docs](http://hackage.haskell.org/package/dlist-0.7.1.2/docs/Data-DList.html) show that `DList` is defined with `data`. However, it is actually done with `newtype`.

**Comment by spl** [comment]
This is a Haddock “feature.” If the `newtype` is abstract (i.e. the constructor is not exported), Haddock presents it as a `data`. See the `N4` example [here](https://www.haskell.org/haddock/Test/Test.html#2).

I would probably prefer it shown as a `newtype`, since that conveys something about strictness, whereas `data` is more general and doesn't convey much. However, you could argue that, since the type is abstract, you can't pattern-match on it, and you already don't know how strict the functions are, so displaying it as `newtype` actually breaks the abstract guarantee _and_ doesn't really tell you much.

If you're motivated enough, you could report a [Haddock issue](http://trac.haskell.org/haddock), though I think this has been around as long as Haddock has.

**Comment by andrewthad** [comment]
Ah! Thanks for letting me know. That is a bizarre feature.
